config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
mount Sidekiq::Web => '/sidekiq'
  resources :companies do
  	member do
  		put :scrap_content
  	end
  end

  resources :contents do
  	collection do
  		get :search
  		get :download
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :contents
end

app/models/content.rb
class Content < ApplicationRecord
	belongs_to :company
	searchkick synonyms: [["Location", "Offices"], ["Offices","Market Presence"],
["Products", "Services"], ["Solutions", "Technologies"], ["Business Offerings", "Business Lines"],
["About","Company Description"],
["Website", "Homepage URL"],
["News", "Blog"], ["Press", "Press Release"],
["Investors", "Seed"], ["Series A", "Series B"], ["Series C", "Investment"], ["Capital Raised", "Fund Raised"], ["Fund Raised","Revenue"],
["Partners", "Partnership"], ["Collaboration", "Partnered"], ["Channels", "Partnered"],
["Contact", "Support"], ["Support", "Call"],
["Customers", "Consumers"],["Clients", "Users"],
["Award", "Accolade"], ["Accolade","Win"],
["Sector", "Vertical"],["Vertical","Industries"]]
	
	def self.to_csv(content,query)
		CSV.generate do |csv|
	      csv << ["Query",query]
	      content.each do |data|
	        csv << [data]
	      end
	    end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy, :scrap_content]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.description = MetaInspector.new(@company.home_page).best_description
    @company.metadata = MetaInspector.new(@company.home_page).meta
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    @company.description = MetaInspector.new(@company.home_page).best_description
    @company.metadata = MetaInspector.new(@company.home_page).meta
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def scrap_content
    Content.where(company_id: @company.id).delete_all
    ScrapWorker.perform_async(@company.id)
    redirect_to @company
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :home_page, :verified)
    end
end

app/controllers/contents_controller.rb
require 'matrix'
require 'tf-idf-similarity'
class ContentsController < ApplicationController

	def index
	end

	def search
		@contents = Content.search params["query"], where: {company_id: params[:company_id].to_i}
		@contents = @contents.map(&:data).uniq
		return if @contents == []
		corpus = Lda::Corpus.new
		@contents.each do |content|
			corpus.add_document(Lda::TextDocument.new(corpus, content))
		end
		lda = Lda::Lda.new(corpus)
		lda.verbose = false
		lda.num_topics = (2)
		lda.em('random')
		topics = lda.top_words(20)
		@topics = topics.values.flatten.select { |word| word.length > 2}
		if params[:method_id].to_i == 0
			carrot2 = Carrot2.new
			clusters = carrot2.cluster(@contents)["clusters"]
			doc_clusters = clusters.to_a.map { |val| val["documents"] }
			@clustered_documents_map = doc_clusters.map do |cluster|
				get_mean_documents(cluster.map(&:to_i))			
			end
			@clustered_documents = @clustered_documents_map.each_with_index.map do |cluster,i|
				cluster.map do |doc|
					doc_clusters[i][doc].to_i
				end
			end
			@clustered_documents =  @clustered_documents[0].zip(*@clustered_documents[1..-1]).flatten.uniq.compact	
			@contents = @clustered_documents.map do |doc|
				@contents[doc]
			end
		end
		respond_to do |format|
	      format.html
	      format.csv { send_data Content.to_csv(@contents,params[:query]), filename: "#{Company.find(params[:company_id]).name} #{params[:query]}.csv" }
		end
	end


	def get_mean_documents(doc)
		corpus = doc.map { |content| TfIdfSimilarity::Document.new(@contents[content])}
		model = TfIdfSimilarity::TfIdfModel.new(corpus)
		model.similarity_matrix
			.row_vectors()
			.map(&:to_a)
			.each_with_index
			.map { |x,i| [i,x.sum] }
			.sort_by(&:last).reverse.map(&:first)[0..1]
	end

	def download
		puts params
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :company_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :home_page %>
    <%= form.text_field :home_page, id: :company_home_page, class: "form-control" %>
  </div>

  <div class="form-check">
    <%= form.check_box :verified, id: :company_verified, class: "form-check-input" %>
    <%= form.label :verified, class: "form-check-label" %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Home page</th>
      <th>Verified</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.home_page %></td>
        <td><%= company.verified %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Home page:</strong>
  <%= @company.home_page %>
</p>

<p>
  <strong>Description:</strong>
  <%= @company.description %>
</p>

<p>
  	<strong>MetaData:</strong>
</p>
  	<table class="table table-striped table-bordered table-dark">
  	<tbody>
  	<% @company.metadata.each do |k,v|%>
	  	<% if v %>
		  	<tr>
			  	<td><%=k%></td>
			  	<td><%=v%></td>
			</tr>
	  	<% end %>
	<% end %>
	</tbody>
  </table>


<p>
  <strong>Verified:</strong>
  <%= @company.verified %>
</p>


<%= link_to 'Extract Content', scrap_content_company_path(@company), method: :put %> |

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/contents/index.html.erb
<div class="content_search">
<%= form_tag("/contents/search", method: "get", class: "form-inline") do %>
  <%= text_field_tag :query, nil ,class: "form-control", placeholder: "Query" %>
  <%= select_tag(:company_id, options_for_select(Company.all.map { |com| [com.name, com.id] }), {class: "form-control"}) %>
  <%= submit_tag "search", class: "btn btn-primary" %>
<% end %>
</div>

app/views/contents/search.html.erb
<div class="content_search">
	<%= form_tag("/contents/search", method: "get", class: "form-inline") do %>
	  <%= text_field_tag :query, nil ,class: "form-control", placeholder: "Query" %>
	  <%= select_tag(:company_id, options_for_select(Company.all.map { |com| [com.name, com.id] }), {class: "form-control"}) %>
	  <%= select_tag(:method_id, options_for_select([["Cluster Mean", 0],["Raw Document", 1]]), class: "form-control") %>
	  <%= submit_tag "search", class: "btn btn-primary" %>
	  <%= link_to "Download", search_contents_path(query: params[:query],method_id: params[:method_id], company_id: params[:company_id], format: :csv), class: "btn btn-primary" %>
	<% end %>
	<div class="card">
		<div class="card-header">LDA Keywords</div>
	  <div class="card-body">
		<% @topics.try(:each) do |topic| %>
			<span class="badge badge-primary"><%= topic %></span>
		<% end %>
	  </div>
	</div>

    
	<% @contents.try(:each) do |content| %>
	<div class="card">
	  <div class="card-body">
		<%= content %>
	  </div>
	</div>
	<% end %>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DNACapitalCrawler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <a class="navbar-brand" href="/companies">DNA Capitals</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/companies">Companies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contents">Content</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="row justify-content-center">
  <div class="col-11">
    <%= yield %>
    </div>
    </div>
  </body>
</html>